[package]
name = "libre-flypy"
authors = ["OverflowCat"]
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
